language: php
sudo: false
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install: composer install

script:
  - mkdir -p build/logs
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpunit ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
